#devlopment repository
name: trigger test in another reposiroty
on: workflow_dispatch
jobs: 
  trigger-test:
    runs-on: ubuntu-latest
    #build container #deploy container
    steps: 
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2 
        with:
          token: ${{ secrets.ACTIOn-TOKEN1}}
          repository: naveen184/triggerrepo
          event-type: my-event
          clint-payload: '{"github": ${{ tojson(github)}}}'
